### ISSUE TITLE
dependency "lumen-elocache" causes this to break when running `composer install`

### ISSUE THREAD

**Issue by cjwilburn** [rlacerda83/lumen-email-microservice#5]
I'm guessing that is because it is `lumem-elocache` I can submit a PR for this if you'd like.

**Comment by rlacerda83** [comment]
what is your php version?

**Comment by cjwilburn** [comment]
5.6.23

**Comment by rlacerda83** [comment]
Strange! 

I cloned the project and performed the composer install and did not issue.
After I performed the composer update, and had no error.

**Comment by cjwilburn** [comment]
Strange indeed! I saw the issue for the first time recently after months of no problems. I'll try to replicate it and send you the results.
